# Generated by Django 5.1.7 on 2025-03-13 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
