# Generated by Django 5.1.7 on 2025-03-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_products_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='name',
        ),
    ]
