# Generated by Django 5.1.7 on 2025-03-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_products_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='description',
            field=models.CharField(db_column='Description', max_length=200, null=True),
        ),
    ]
