# Generated by Django 5.1.7 on 2025-03-13 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_products_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='name',
            field=models.CharField(db_column='Name', max_length=50, null=True),
        ),
    ]
