# Generated by Django 5.1.7 on 2025-03-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_products_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='customer/imgs/default.jpg', upload_to='products/imgs'),
        ),
        migrations.AddField(
            model_name='products',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
