# Generated by Django 5.1.7 on 2025-03-19 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_products_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='incart',
            field=models.BooleanField(default=False),
        ),
    ]
