# Generated by Django 5.1.7 on 2025-03-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_products_incart'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='cart_quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
